### ISSUE TITLE
Write reuable python function to link DOIs and PMIDs to author affiliation RORs

### ISSUE THREAD

**Issue by jmelot** [jmelot/SoftwareImpactHackathon2023_InstitutionalOSS#17]
Now that we're out of hackathon mode, I think it would be useful to refactor our code so we can call a single script per data source to do the end to end data retrieval for that source (see #16).

Kaitlyn wrote several very helpful scripts to map DOIs to author affiliations (see `resources/rrid_dataset_mapped_to_openalex.R` and `resources/joss_dataset_mapped_to_openalex.R`). I think it would be useful to refactor these a little bit such that we had a reusable python function like so:

```
def work_to_affiliation_rors(ident: str, ident_type: str) -> list:
    """
    Given a work identifier and the type of that identifier (one of 'doi' or 'pmid'), 
    retrieves the ROR ids of the author affiliations for that work.
    :param ident: Identifier for a work
    :param ident_type: Type of that identifier (either 'doi' or 'pmid')
    :return: List of ROR ids corresponding to author affiliations of that work 
    """
    pass
```

We could then reuse this function in the various data pipelines that depend on this capability.

@kaitlynhair I would be grateful for your thoughts here. I am a little torn - I want to make sure everyone feels comfortable continuing to contribute if they like and I think you said you currently prefer R, but at the same time I think we should converge on a single language for our core data pipelines (this probably matters less for data analysis scripts we might use in the paper, for example), and I think python is something at least most people on the team have some familiarity with. What do you think - and/or, would you be interested in taking this on?

**Comment by kaitlynhair** [comment]
@jmelot I'm happy for things to move across to Python. Totally agree it makes sense to have it all in one pipeline!
I'll have a go over the next couple of days and update you on how I get on!

**Comment by jmelot** [comment]
Hey, wanted to check whether you'd had a chance to look at this. If not, no worries, I can knock it out this weekend real quick (trying to get a draft of everything together for people to review in next couple of days), I can ask you to review to make sure I didn't miss anything!
