### ISSUE TITLE
Write single script that runs the `by_name` and `human_curated` pipelines end to end

### ISSUE THREAD

**Issue by jmelot** [jmelot/SoftwareImpactHackathon2023_InstitutionalOSS#22]
Right now this is two scripts in [here](https://github.com/jmelot/SoftwareImpactHackathon2023_InstitutionalOSS/tree/main/resources/ruby). It would be nice to have this all in one script that takes Anita's spreadsheet as input and outputs the final set of software to ROR links in the form consumed by `consolidate_links.py`. I think it would also be nice to convert this to python, now that we are out of hackathon mode, for the sake of consistency (and we could use #22 here and in #20). Would you be interested in working on this @sfisher ?

**Comment by sfisher** [comment]
Thanks @jmelot, sorry for the late reply.  I hope I'll have some time later this week to look at this, if not I may have some time next week to work through it.  Is there a specific date you're targeting cleanup by?

**Comment by jmelot** [comment]
Closed via https://github.com/jmelot/SoftwareImpactHackathon2023_InstitutionalOSS/pull/30 (and manual merging)
